baseURL = "https://hugo-paper.vercel.app/"
# title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "Paper"

[params]
  color = 'linen'

  twitter = 'crichards2000'
  github = 'chrisrichards'
  mastodon = '@chrisrichards@mastodon.social'

  avatar = 'chris@chrisrichards.co.uk'
  name = 'Chris'
  bio = 'Discover fresh context'

  [[params.socials]]
  name = "github"
  url = "https://github.com/chrisrichards"

  [[params.socials]]
  name = "mastodon"
  url = "https://mastodon.social/@chrisrichards"

  [[params.socials]]
  name = "LinkedIn"
  url = "https://www.printables.com/social/94683-chris-r"

  [[params.socials]]
  name = "printables"
  url = "https://www.printables.com/social/94683-chris-r"

  [[params.socials]]
  name = "email"
  url = "mailto:chris@chrisrichards.co.uk"

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
